"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def generator_for_fibonacci_term_no_greater_than_four_million():
    a = 1
    b = 2

    while b <= 4000000:
        # yield b value before generating new b value so that 2 is considered.
        if b % 2 == 0:
            yield b
        a, b = b, a + b

sum = 0
for i in generator_for_fibonacci_term_no_greater_than_four_million():
    sum += i

print("the answer is", sum)